on:
  repository_dispatch:
    types: [update_data]

jobs:
  update:
    name: Submodule Update
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main
          persist-credentials: false
          fetch-depth: 0
          submodules: recursive

      - name: Git Config
        run: |
          git config --local user.name "growthers"
          git config --local user.email "noreply@growthers.dev"

      - name: Git Submodule Update
        run: git submodule update --remote --recursive

      - name: Git Add
        run: git add --all

      - name: Git Commit
        run: git commit -m "[Auto] Update Data"

      - name: Git Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main

  build:
    name: Deploy
    runs-on: ubuntu-latest
    needs:
      - update

    steps:
      - name: Request
        run: |
          curl -H "Authorization: token ${{ secrets.DISPATCH_TOKEN }}" -H "Accept: application/vnd.github.v3+json"  ${{ secrets.DISPATCHES_URL }} -d '{"event_type":"deploy"}'
